diaexpert/Controllers/admin/doctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using diaexpert.Models;

namespace diaexpert.Controllers.admin
{
    public class doctorsController : Controller
    {
        private diacontext db = new diacontext();

        // GET: doctors
        public ActionResult Index()
        {
            List<doctor> doclist = db.doc.ToList();
            foreach(doctor d in doclist)
            {
                if (d.photo == null)
                {
                    d.photo = "~/Images/doctorimages/noimage.png";
                }
            }
            return View(doclist);
        }

        // GET: doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doc.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: doctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,mobile,address,credentials,level,photo,pincode,lat,lan,timestampe")] doctor doctor, HttpPostedFileBase[] file)
        {
            if (ModelState.IsValid)
            {
                foreach (HttpPostedFileBase files in file)
                {
                    if (file == null)
                    {
                        ModelState.AddModelError("File", "Please Upload Your file");
                        ViewBag.message = "Please pick a file for upload!";
                    }
                    else if (files.ContentLength > 0)
                    {
                        int MaxContentLength = 1024 * 1024 * 3; //3 MB
                        string[] AllowedFileExtensions = new string[] { ".jpg", ".txt", ".gif", ".png", ".pdf" };

                        if (!AllowedFileExtensions.Contains(files.FileName.Substring(files.FileName.LastIndexOf('.'))))
                        {
                            ModelState.AddModelError("File", "Please use file of type: " + string.Join(", ", AllowedFileExtensions));
                            ViewBag.Message = "Wrong file Type";
                        }

                        else if (files.ContentLength > MaxContentLength)
                        {
                            ModelState.AddModelError("File", "Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                            ViewBag.Message = "Your file is too large, maximum allowed size is: " + MaxContentLength + " MB";
                        }
                        else
                        {
                            var filename = Path.GetFileName(files.FileName);

                            var path = Path.Combine(Server.MapPath("~/Images/doctorimages"), filename);
                            files.SaveAs(path);
                            doctor.photo = "/Images/doctorimages/" + filename;
                        }
                    }
                }
                    db.doc.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        // GET: doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doc.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,mobile,address,credentials,level,photo,pincode,lat,lan,timestampe")] doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            doctor doctor = db.doc.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            doctor doctor = db.doc.Find(id);
            db.doc.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

diaexpert/Controllers/client/doctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Xml.Schema;
using diaexpert.Models;

namespace diaexpert.Controllers.client
{
    public class doctorsController : ApiController
    {
        private diacontext db = new diacontext();

        // GET: api/doctors
        public IQueryable<doctor> Getdoc()
        {
            return db.doc;
        }

        // GET: api/doctors/5
        [ResponseType(typeof(doctor))]
        public IHttpActionResult Getdoctor(int id)
        {
            doctor doctor = db.doc.Find(id);
            if (doctor == null)
            {
                return NotFound();
            }

            return Ok(doctor);
        }

        // PUT: api/doctors/5
        //[ResponseType(typeof(void))]
        //public IHttpActionResult Putdoctor(int id, doctor doctor)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return BadRequest(ModelState);
        //    }

            //    if (id != doctor.id)
            //    {
            //        return BadRequest();
            //    }

            //    db.Entry(doctor).State = EntityState.Modified;

            //    try
            //    {
            //        db.SaveChanges();
            //    }
            //    catch (DbUpdateConcurrencyException)
            //    {
            //        if (!doctorExists(id))
            //        {
            //            return NotFound();
            //        }
            //        else
            //        {
            //            throw;
            //        }
            //    }

            //    return StatusCode(HttpStatusCode.NoContent);
            //}

            //// POST: api/doctors
            //[ResponseType(typeof(doctor))]
            //public IHttpActionResult Postdoctor(doctor doctor)
            //{
            //    if (!ModelState.IsValid)
            //    {
            //        return BadRequest(ModelState);
            //    }

            //    db.doc.Add(doctor);
            //    db.SaveChanges();

            //    return CreatedAtRoute("DefaultApi", new { id = doctor.id }, doctor);
            //}

            //// DELETE: api/doctors/5
            //[ResponseType(typeof(doctor))]
            //public IHttpActionResult Deletedoctor(int id)
            //{
            //    doctor doctor = db.doc.Find(id);
            //    if (doctor == null)
            //    {
            //        return NotFound();
            //    }

            //    db.doc.Remove(doctor);
            //    db.SaveChanges();

            //    return Ok(doctor);
            //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool doctorExists(int id)
        {
            return db.doc.Count(e => e.id == id) > 0;
        }
    }
}

diaexpert/Views/doctors/Create.cshtml
@model diaexpert.Models.doctor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","doctors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>doctor</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-10">
            @Html.TextBox("file", "", new { type = "file", @multiple = "multiple" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.credentials, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.credentials, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.credentials, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.level, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.level, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.level, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.pincode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.pincode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.pincode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.timestampe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.timestampe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.timestampe, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

diaexpert/Views/doctors/Delete.cshtml
@model diaexpert.Models.doctor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.credentials)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.credentials)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.timestampe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timestampe)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

diaexpert/Views/doctors/Details.cshtml
@model diaexpert.Models.doctor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.credentials)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.credentials)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.timestampe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timestampe)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

diaexpert/Views/doctors/Edit.cshtml
@model diaexpert.Models.doctor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.credentials, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.credentials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.credentials, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.level, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pincode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pincode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pincode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.timestampe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.timestampe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.timestampe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

diaexpert/Views/doctors/Index.cshtml
@model IEnumerable<diaexpert.Models.doctor>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.mobile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.credentials)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.level)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.pincode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.timestampe)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        <img src="@Url.Content(item.photo)" width="100" />
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.mobile)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.address)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.credentials)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.level)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.pincode)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.lat)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.lan)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.timestampe)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
        @Html.ActionLink("Details", "Details", new { id = item.id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.id })
    </td>
</tr>
}

</table>